service: backend
runtime: nodejs20
env: standard
instance_class: F1
entrypoint: npm start

env_variables:
  NODE_ENV: "production"
  DB_HOST: "ep-long-field-a1m2i866-pooler.ap-southeast-1.aws.neon.tech"
  DB_USER: "neondb_owner"
  DB_PASSWORD: "npg_Zri0hDWoNH2J"
  DB_NAME: "neondb"
  DB_PORT: "5432"
  DB_SSL: "true"
  JWT_SECRET: "e35903c5806a75d842193f3bec40b0b04d58f3a8f9cf95ab80e73719d33e93a9069269bde1c079eab4c78a75aa0ec7d402657407efbd675eeb7f09862948fcf1"
  JWT_EXPIRES_IN: "24h"
  ENCRYPTION_KEY: "7x!A%D*G-KaPdSgVkYp3s6v9y$B&E(H+"
  ACCESS_KEY_ID: "<YOUR_AWS_ACCESS_KEY>"
  SECRET_ACCESS_KEY: "<YOUR_AWS_SECRET_KEY>"
  S3_BUCKET: "<YOUR_BUCKET_NAME>"
  S3_BUCKET_URL: "<YOUR_BUCKET_URL>"
  FRONTEND_URL: "https://frontend-dot-project-ab-dev.el.r.appspot.com"
